/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

/*Seccion de codigo de usuario*/
package analizadorlex;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

//clase de los token devueltos
class Yytoken {
    Yytoken (int numToken,String token, String tipo, int linea, int columna){
        //Contador para el número de tokens reconocidos
        this.numToken = numToken;
        //String del token reconocido
        this.token = new String(token);
        //Tipo de componente léxico encontrado
        this.tipo = tipo;
        //Número de linea
        this.linea = linea;
        //Columna donde empieza el primer carácter del token
        this.columna = columna;
    }
    //Métodos de los atributos de la clase
    public int numToken;
    public String token;
    public String tipo;
    public int linea;
    public int columna;
    //Metodo que devuelve los datos necesarios que escribiremos en un archive de salida
    public String toString() {
        return "Token#"+numToken+": "+token+"|"+"  Componente Lexico:  "+"|"+tipo+" ["+"Linea: "+(linea)+ "]";
    }
}

//--------------------------------------
class ErroresC {
    ErroresC (String token, String tipo, int linea){
        
        //String del token reconocido
        this.token = new String(token);
        //Tipo de componente léxico encontrado
        this.tipo = tipo;
        //Número de linea
        this.linea = linea;

    }
    //Métodos de los atributos de la clase
    public String token;
    public String tipo;
    public int linea;

    //Metodo que devuelve los datos necesarios que escribiremos en un archive de salida
    public String toString() {
        return "Error " + tipo +" |  \" "+token+" \"  | ["+"Linea: "+(linea)+ "] : Se ha introducido un caracter no valido, sustituyalo por un caracter valido";
    }
}



/* Seccion de opciones y declaraciones de JFlex */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
public class AnalizadorLexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\5\2\0\1\6\22\0\1\4\1\72\1\102\1\3"+
    "\1\107\1\112\1\70\1\115\1\73\1\74\1\66\1\64\1\100\1\65"+
    "\1\110\1\67\12\2\1\101\1\77\1\76\1\63\1\75\1\114\1\117"+
    "\1\17\1\27\1\14\1\40\1\16\1\57\1\54\1\30\1\32\2\1"+
    "\1\46\1\45\1\53\1\33\1\62\1\1\1\15\1\41\1\20\1\34"+
    "\1\31\1\50\1\56\1\42\1\1\1\105\1\122\1\106\1\116\1\111"+
    "\1\120\1\12\1\21\1\7\1\35\1\11\1\60\1\52\1\22\1\24"+
    "\2\1\1\44\1\43\1\51\1\25\1\61\1\1\1\10\1\36\1\13"+
    "\1\26\1\23\1\47\1\55\1\37\1\1\1\103\1\71\1\104\1\121"+
    "\42\0\1\123\6\0\1\124\3\0\1\125\3\0\1\126\3\0\1\127"+
    "\12\0\1\113\uff40\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\26\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\0\35\1\1\52\31\1\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\0"+
    "\1\63\1\64\4\1\1\65\5\1\1\66\40\1\1\67"+
    "\25\1\1\70\1\1\1\71\1\72\5\1\1\73\1\74"+
    "\1\75\1\1\1\76\15\1\1\77\35\1\1\100\2\1"+
    "\1\101\1\1\1\102\11\1\1\103\7\1\1\104\2\1"+
    "\1\105\16\1\1\106\11\1\1\107\5\1\1\110\3\1"+
    "\1\111\5\1\1\112\6\1\1\113\1\114\6\1\1\115"+
    "\1\116\1\117\4\1\1\120\2\1\1\121\3\1\1\122"+
    "\2\1\1\123\3\1\1\124\1\125\4\1\1\126\1\127";

  private static int [] zzUnpackAction() {
    int [] result = new int[365];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\130\0\260\0\u0108\0\u0160\0\u01b8\0\u0210\0\u0268"+
    "\0\u02c0\0\u0318\0\u0370\0\u03c8\0\u0420\0\u0478\0\u04d0\0\u0528"+
    "\0\u0580\0\u05d8\0\u0630\0\u0688\0\u06e0\0\u0738\0\u0790\0\u07e8"+
    "\0\u0840\0\u0898\0\u08f0\0\u0948\0\u09a0\0\u09f8\0\u0a50\0\u0aa8"+
    "\0\u0b00\0\u0160\0\u0160\0\u0b58\0\u0bb0\0\u0160\0\u0c08\0\u0c60"+
    "\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160"+
    "\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160"+
    "\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160"+
    "\0\u0160\0\u0108\0\u0cb8\0\u0d10\0\u0d68\0\u0dc0\0\u0e18\0\u0e70"+
    "\0\u0ec8\0\u0f20\0\u0f78\0\u0fd0\0\u1028\0\u1080\0\u10d8\0\u1130"+
    "\0\u1188\0\u11e0\0\u1238\0\u1290\0\u12e8\0\u1340\0\u1398\0\u13f0"+
    "\0\u1448\0\u14a0\0\u14f8\0\u1550\0\u15a8\0\u1600\0\u1658\0\130"+
    "\0\u16b0\0\u1708\0\u1760\0\u17b8\0\u1810\0\u1868\0\u18c0\0\u1918"+
    "\0\u1970\0\u19c8\0\u1a20\0\u1a78\0\u1ad0\0\u1b28\0\u1b80\0\u1bd8"+
    "\0\u1c30\0\u1c88\0\u1ce0\0\u1d38\0\u1d90\0\u1de8\0\u1e40\0\u1e98"+
    "\0\u1ef0\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160\0\u0160"+
    "\0\u0160\0\u1f48\0\u0160\0\u0160\0\u1fa0\0\u1ff8\0\u2050\0\u20a8"+
    "\0\130\0\u2100\0\u2158\0\u21b0\0\u2208\0\u2260\0\130\0\u22b8"+
    "\0\u2310\0\u2368\0\u23c0\0\u2418\0\u2470\0\u24c8\0\u2520\0\u2578"+
    "\0\u25d0\0\u2628\0\u2680\0\u26d8\0\u2730\0\u2788\0\u27e0\0\u2838"+
    "\0\u2890\0\u28e8\0\u2940\0\u2998\0\u29f0\0\u2a48\0\u2aa0\0\u2af8"+
    "\0\u2b50\0\u2ba8\0\u2c00\0\u2c58\0\u2cb0\0\u2d08\0\u2d60\0\130"+
    "\0\u2db8\0\u2e10\0\u2e68\0\u2ec0\0\u2f18\0\u2f70\0\u2fc8\0\u3020"+
    "\0\u3078\0\u30d0\0\u3128\0\u3180\0\u31d8\0\u3230\0\u3288\0\u32e0"+
    "\0\u3338\0\u3390\0\u33e8\0\u3440\0\u3498\0\u0160\0\u34f0\0\130"+
    "\0\130\0\u3548\0\u35a0\0\u35f8\0\u3650\0\u36a8\0\130\0\130"+
    "\0\130\0\u3700\0\130\0\u3758\0\u37b0\0\u3808\0\u3860\0\u38b8"+
    "\0\u3910\0\u3968\0\u39c0\0\u3a18\0\u3a70\0\u3ac8\0\u3b20\0\u3b78"+
    "\0\130\0\u3bd0\0\u3c28\0\u3c80\0\u3cd8\0\u3d30\0\u3d88\0\u3de0"+
    "\0\u3e38\0\u3e90\0\u3ee8\0\u3f40\0\u3f98\0\u3ff0\0\u4048\0\u40a0"+
    "\0\u40f8\0\u4150\0\u41a8\0\u4200\0\u4258\0\u42b0\0\u4308\0\u4360"+
    "\0\u43b8\0\u4410\0\u4468\0\u44c0\0\u4518\0\u4570\0\130\0\u45c8"+
    "\0\u4620\0\130\0\u4678\0\130\0\u46d0\0\u4728\0\u4780\0\u47d8"+
    "\0\u4830\0\u4888\0\u48e0\0\u4938\0\u4990\0\130\0\u49e8\0\u4a40"+
    "\0\u4a98\0\u4af0\0\u4b48\0\u4ba0\0\u4bf8\0\130\0\u4c50\0\u4ca8"+
    "\0\130\0\u4d00\0\u4d58\0\u4db0\0\u4e08\0\u4e60\0\u4eb8\0\u4f10"+
    "\0\u4f68\0\u4fc0\0\u5018\0\u5070\0\u50c8\0\u5120\0\u5178\0\130"+
    "\0\u51d0\0\u5228\0\u5280\0\u52d8\0\u5330\0\u5388\0\u53e0\0\u5438"+
    "\0\u5490\0\130\0\u54e8\0\u5540\0\u5598\0\u55f0\0\u5648\0\130"+
    "\0\u56a0\0\u56f8\0\u5750\0\130\0\u57a8\0\u5800\0\u5858\0\u58b0"+
    "\0\u5908\0\130\0\u5960\0\u59b8\0\u5a10\0\u5a68\0\u5ac0\0\u5b18"+
    "\0\130\0\130\0\u5b70\0\u5bc8\0\u5c20\0\u5c78\0\u5cd0\0\u5d28"+
    "\0\130\0\130\0\130\0\u5d80\0\u5dd8\0\u5e30\0\u5e88\0\130"+
    "\0\u5ee0\0\u5f38\0\130\0\u5f90\0\u5fe8\0\u6040\0\130\0\u6098"+
    "\0\u60f0\0\130\0\u6148\0\u61a0\0\u61f8\0\130\0\130\0\u6250"+
    "\0\u62a8\0\u6300\0\u6358\0\130\0\130";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[365];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\2\5\1\6\1\7\1\10"+
    "\1\11\1\2\1\12\1\13\1\14\1\15\1\2\1\16"+
    "\1\17\1\2\1\20\1\21\2\2\1\22\1\2\1\23"+
    "\1\24\2\2\1\25\1\26\1\2\1\27\1\30\10\2"+
    "\1\31\1\2\1\32\4\2\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\1\76"+
    "\1\77\1\100\1\101\1\0\2\2\4\0\54\2\47\0"+
    "\1\3\126\0\2\102\1\5\1\102\2\0\54\102\202\0"+
    "\1\5\123\0\2\2\4\0\1\2\1\103\1\2\1\104"+
    "\11\2\1\105\36\2\46\0\2\2\4\0\2\2\1\106"+
    "\13\2\1\107\35\2\46\0\2\2\4\0\1\110\34\2"+
    "\1\111\4\2\1\112\3\2\1\113\5\2\46\0\2\2"+
    "\4\0\2\2\1\114\1\115\11\2\1\116\36\2\46\0"+
    "\2\2\4\0\6\2\1\117\1\2\1\120\12\2\1\121"+
    "\30\2\46\0\2\2\4\0\7\2\1\122\14\2\1\123"+
    "\27\2\46\0\2\2\4\0\5\2\1\124\31\2\1\125"+
    "\4\2\1\126\2\2\1\127\4\2\46\0\2\2\4\0"+
    "\7\2\1\130\1\131\12\2\1\132\30\2\46\0\2\2"+
    "\4\0\2\2\1\133\12\2\1\134\1\2\1\135\34\2"+
    "\46\0\2\2\4\0\15\2\1\136\36\2\46\0\2\2"+
    "\4\0\42\2\1\137\6\2\1\140\2\2\46\0\2\2"+
    "\4\0\7\2\1\141\13\2\1\142\1\2\1\143\26\2"+
    "\46\0\2\2\4\0\23\2\1\144\30\2\46\0\2\2"+
    "\4\0\44\2\1\145\3\2\1\140\3\2\46\0\2\2"+
    "\4\0\2\2\1\146\51\2\46\0\2\2\4\0\2\2"+
    "\1\147\1\2\1\150\10\2\1\151\16\2\1\152\1\153"+
    "\2\2\1\154\13\2\46\0\2\2\4\0\7\2\1\155"+
    "\44\2\46\0\2\2\4\0\7\2\1\156\1\2\1\157"+
    "\11\2\1\160\12\2\1\161\1\162\1\2\1\163\12\2"+
    "\46\0\2\2\4\0\1\2\1\164\52\2\46\0\2\2"+
    "\4\0\6\2\1\165\45\2\46\0\2\2\4\0\1\2"+
    "\1\166\14\2\1\167\35\2\46\0\2\2\4\0\6\2"+
    "\1\170\15\2\1\171\27\2\130\0\1\172\127\0\1\173"+
    "\1\174\126\0\1\175\1\0\1\176\125\0\1\177\127\0"+
    "\1\200\127\0\1\201\130\0\1\202\126\0\1\203\127\0"+
    "\1\204\45\0\2\2\4\0\2\2\1\205\51\2\46\0"+
    "\2\2\4\0\27\2\1\206\5\2\1\207\16\2\46\0"+
    "\2\2\4\0\1\210\53\2\46\0\2\2\4\0\4\2"+
    "\1\211\22\2\1\212\21\2\1\213\2\2\46\0\2\2"+
    "\4\0\17\2\1\214\34\2\46\0\2\2\4\0\16\2"+
    "\1\215\35\2\46\0\2\2\4\0\27\2\1\216\24\2"+
    "\46\0\2\2\4\0\26\2\1\217\25\2\46\0\2\2"+
    "\4\0\15\2\1\220\36\2\46\0\2\2\4\0\46\2"+
    "\1\221\5\2\46\0\2\2\4\0\12\2\1\222\41\2"+
    "\46\0\2\2\4\0\34\2\1\223\5\2\1\224\11\2"+
    "\46\0\2\2\4\0\7\2\1\225\44\2\46\0\2\2"+
    "\4\0\32\2\1\226\4\2\1\227\14\2\46\0\2\2"+
    "\4\0\5\2\1\230\46\2\46\0\2\2\4\0\11\2"+
    "\1\211\20\2\1\231\15\2\1\232\3\2\46\0\2\2"+
    "\4\0\25\2\1\233\26\2\46\0\2\2\4\0\24\2"+
    "\1\234\27\2\46\0\2\2\4\0\32\2\1\235\21\2"+
    "\46\0\2\2\4\0\31\2\1\217\22\2\46\0\2\2"+
    "\4\0\23\2\1\236\30\2\46\0\2\2\4\0\47\2"+
    "\1\237\4\2\46\0\2\2\4\0\20\2\1\240\33\2"+
    "\46\0\2\2\4\0\36\2\1\241\5\2\1\242\7\2"+
    "\46\0\2\2\4\0\13\2\1\243\40\2\46\0\2\2"+
    "\4\0\43\2\1\244\10\2\46\0\2\2\4\0\15\2"+
    "\1\245\36\2\46\0\2\2\4\0\1\2\1\246\52\2"+
    "\46\0\2\2\4\0\15\2\1\247\36\2\46\0\2\2"+
    "\4\0\21\2\1\250\32\2\46\0\2\2\4\0\45\2"+
    "\1\251\6\2\46\0\2\2\4\0\23\2\1\252\30\2"+
    "\46\0\2\2\4\0\6\2\1\253\45\2\46\0\2\2"+
    "\4\0\23\2\1\254\30\2\46\0\2\2\4\0\1\255"+
    "\26\2\1\256\21\2\1\257\2\2\46\0\2\2\4\0"+
    "\4\2\1\260\36\2\1\261\10\2\46\0\2\2\4\0"+
    "\3\2\1\262\50\2\46\0\2\2\4\0\34\2\1\263"+
    "\17\2\46\0\2\2\4\0\3\2\1\264\50\2\46\0"+
    "\2\2\4\0\2\2\1\265\51\2\46\0\2\2\4\0"+
    "\15\2\1\266\36\2\46\0\2\2\4\0\5\2\1\267"+
    "\24\2\1\270\15\2\1\271\3\2\46\0\2\2\4\0"+
    "\11\2\1\260\33\2\1\272\6\2\46\0\2\2\4\0"+
    "\10\2\1\273\43\2\46\0\2\2\4\0\36\2\1\274"+
    "\15\2\46\0\2\2\4\0\10\2\1\275\43\2\46\0"+
    "\2\2\4\0\7\2\1\276\44\2\46\0\2\2\4\0"+
    "\23\2\1\277\30\2\46\0\2\2\4\0\16\2\1\300"+
    "\35\2\46\0\2\2\4\0\24\2\1\301\27\2\46\0"+
    "\2\2\4\0\16\2\1\302\35\2\46\0\2\2\4\0"+
    "\52\2\1\303\1\2\46\0\2\2\4\0\24\2\1\304"+
    "\27\2\46\0\2\2\4\0\53\2\1\305\141\0\1\306"+
    "\34\0\2\2\4\0\3\2\1\307\50\2\46\0\2\2"+
    "\4\0\2\2\1\310\51\2\46\0\2\2\4\0\35\2"+
    "\1\311\16\2\46\0\2\2\4\0\35\2\1\312\16\2"+
    "\46\0\2\2\4\0\16\2\1\313\35\2\46\0\2\2"+
    "\4\0\2\2\1\314\51\2\46\0\2\2\4\0\4\2"+
    "\1\315\47\2\46\0\2\2\4\0\42\2\1\316\11\2"+
    "\46\0\2\2\4\0\2\2\1\317\51\2\46\0\2\2"+
    "\4\0\4\2\1\320\47\2\46\0\2\2\4\0\4\2"+
    "\1\321\47\2\46\0\2\2\4\0\35\2\1\322\16\2"+
    "\46\0\2\2\4\0\2\2\1\323\51\2\46\0\2\2"+
    "\4\0\30\2\1\324\23\2\46\0\2\2\4\0\10\2"+
    "\1\325\43\2\46\0\2\2\4\0\7\2\1\310\44\2"+
    "\46\0\2\2\4\0\37\2\1\311\14\2\46\0\2\2"+
    "\4\0\37\2\1\326\14\2\46\0\2\2\4\0\24\2"+
    "\1\327\27\2\46\0\2\2\4\0\7\2\1\330\44\2"+
    "\46\0\2\2\4\0\11\2\1\331\42\2\46\0\2\2"+
    "\4\0\44\2\1\332\7\2\46\0\2\2\4\0\7\2"+
    "\1\317\44\2\46\0\2\2\4\0\11\2\1\320\42\2"+
    "\46\0\2\2\4\0\11\2\1\321\42\2\46\0\2\2"+
    "\4\0\37\2\1\333\14\2\46\0\2\2\4\0\7\2"+
    "\1\323\44\2\46\0\2\2\4\0\33\2\1\334\20\2"+
    "\46\0\2\2\4\0\3\2\1\335\50\2\46\0\2\2"+
    "\4\0\15\2\1\336\36\2\46\0\2\2\4\0\35\2"+
    "\1\337\16\2\46\0\2\2\4\0\17\2\1\340\34\2"+
    "\46\0\2\2\4\0\4\2\1\341\47\2\46\0\2\2"+
    "\4\0\10\2\1\342\43\2\46\0\2\2\4\0\23\2"+
    "\1\343\30\2\46\0\2\2\4\0\37\2\1\344\14\2"+
    "\46\0\2\2\4\0\25\2\1\345\26\2\46\0\2\2"+
    "\4\0\11\2\1\341\42\2\46\0\2\2\4\0\15\2"+
    "\1\346\36\2\46\0\2\2\4\0\4\2\1\347\47\2"+
    "\46\0\2\2\4\0\15\2\1\350\36\2\46\0\2\2"+
    "\4\0\34\2\1\351\17\2\46\0\2\2\4\0\1\2"+
    "\1\352\52\2\46\0\2\2\4\0\17\2\1\353\34\2"+
    "\46\0\2\2\4\0\35\2\1\354\16\2\46\0\2\2"+
    "\4\0\2\2\1\355\51\2\46\0\2\2\4\0\4\2"+
    "\1\356\47\2\46\0\2\2\4\0\23\2\1\357\30\2"+
    "\46\0\2\2\4\0\11\2\1\360\42\2\46\0\2\2"+
    "\4\0\23\2\1\361\30\2\46\0\2\2\4\0\36\2"+
    "\1\362\15\2\46\0\2\2\4\0\6\2\1\363\45\2"+
    "\46\0\2\2\4\0\25\2\1\364\26\2\46\0\2\2"+
    "\4\0\37\2\1\365\14\2\46\0\2\2\4\0\7\2"+
    "\1\366\44\2\46\0\2\2\4\0\11\2\1\367\42\2"+
    "\46\0\2\2\4\0\40\2\1\370\13\2\46\0\2\2"+
    "\4\0\41\2\1\371\12\2\46\0\2\2\4\0\43\2"+
    "\1\372\10\2\46\0\2\2\4\0\17\2\1\373\34\2"+
    "\46\0\2\2\4\0\45\2\1\374\6\2\46\0\2\2"+
    "\4\0\25\2\1\375\26\2\46\0\2\2\4\0\4\2"+
    "\1\376\47\2\46\0\2\2\4\0\2\2\1\377\51\2"+
    "\46\0\2\2\4\0\17\2\1\u0100\34\2\46\0\2\2"+
    "\4\0\1\2\1\u0101\52\2\46\0\2\2\4\0\2\2"+
    "\1\u0102\51\2\46\0\2\2\4\0\16\2\1\u0103\35\2"+
    "\46\0\2\2\4\0\2\2\1\u0104\51\2\46\0\2\2"+
    "\4\0\15\2\1\u0105\36\2\46\0\2\2\4\0\11\2"+
    "\1\u0106\42\2\46\0\2\2\4\0\7\2\1\377\44\2"+
    "\46\0\2\2\4\0\25\2\1\u0107\26\2\46\0\2\2"+
    "\4\0\6\2\1\u0108\45\2\46\0\2\2\4\0\7\2"+
    "\1\u0102\44\2\46\0\2\2\4\0\24\2\1\u0109\27\2"+
    "\46\0\2\2\4\0\7\2\1\u0104\44\2\46\0\2\2"+
    "\4\0\23\2\1\u010a\30\2\46\0\2\2\4\0\14\2"+
    "\1\u010b\37\2\46\0\2\2\4\0\42\2\1\u010c\11\2"+
    "\46\0\2\2\4\0\26\2\1\u010d\25\2\46\0\2\2"+
    "\4\0\27\2\1\u010e\24\2\46\0\2\2\4\0\22\2"+
    "\1\u010f\31\2\46\0\2\2\4\0\44\2\1\u0110\7\2"+
    "\46\0\2\2\4\0\31\2\1\u0111\22\2\46\0\2\2"+
    "\4\0\32\2\1\u010e\21\2\46\0\2\2\4\0\34\2"+
    "\1\u0112\17\2\46\0\2\2\4\0\1\2\1\u0113\52\2"+
    "\46\0\2\2\4\0\42\2\1\u0114\11\2\46\0\2\2"+
    "\4\0\2\2\1\u0115\51\2\46\0\2\2\4\0\4\2"+
    "\1\u0116\47\2\46\0\2\2\4\0\35\2\1\u0117\16\2"+
    "\46\0\2\2\4\0\35\2\1\u0118\16\2\46\0\2\2"+
    "\4\0\52\2\1\u0119\1\2\46\0\2\2\4\0\1\u011a"+
    "\53\2\46\0\2\2\4\0\36\2\1\u011b\15\2\46\0"+
    "\2\2\4\0\6\2\1\u011c\45\2\46\0\2\2\4\0"+
    "\44\2\1\u011d\7\2\46\0\2\2\4\0\7\2\1\u011e"+
    "\44\2\46\0\2\2\4\0\11\2\1\u0116\42\2\46\0"+
    "\2\2\4\0\37\2\1\u011f\14\2\46\0\2\2\4\0"+
    "\37\2\1\u0120\14\2\46\0\2\2\4\0\53\2\1\u0119"+
    "\46\0\2\2\4\0\5\2\1\u0121\46\2\46\0\2\2"+
    "\4\0\4\2\1\u0122\47\2\46\0\2\2\4\0\11\2"+
    "\1\u0123\42\2\46\0\2\2\4\0\1\2\1\u0124\52\2"+
    "\46\0\2\2\4\0\35\2\1\u0125\16\2\46\0\2\2"+
    "\4\0\6\2\1\u0126\45\2\46\0\2\2\4\0\37\2"+
    "\1\u0127\14\2\46\0\2\2\4\0\2\2\1\u0128\51\2"+
    "\46\0\2\2\4\0\1\2\1\u0129\52\2\46\0\2\2"+
    "\4\0\2\2\1\u012a\51\2\46\0\2\2\4\0\34\2"+
    "\1\u012b\17\2\46\0\2\2\4\0\42\2\1\u012c\11\2"+
    "\46\0\2\2\4\0\7\2\1\u0128\44\2\46\0\2\2"+
    "\4\0\6\2\1\u012d\45\2\46\0\2\2\4\0\7\2"+
    "\1\u012e\44\2\46\0\2\2\4\0\36\2\1\u012f\15\2"+
    "\46\0\2\2\4\0\44\2\1\u0130\7\2\46\0\2\2"+
    "\4\0\15\2\1\u0131\36\2\46\0\2\2\4\0\4\2"+
    "\1\u0132\47\2\46\0\2\2\4\0\15\2\1\u0133\36\2"+
    "\46\0\2\2\4\0\23\2\1\u0134\30\2\46\0\2\2"+
    "\4\0\11\2\1\u0132\42\2\46\0\2\2\4\0\23\2"+
    "\1\u0135\30\2\46\0\2\2\4\0\3\2\1\u0136\50\2"+
    "\46\0\2\2\4\0\16\2\1\u0137\35\2\46\0\2\2"+
    "\4\0\2\2\1\u0138\51\2\46\0\2\2\4\0\42\2"+
    "\1\u0139\11\2\46\0\2\2\4\0\3\2\1\u013a\50\2"+
    "\46\0\2\2\4\0\15\2\1\u013b\36\2\46\0\2\2"+
    "\4\0\13\2\1\u013c\40\2\46\0\2\2\4\0\10\2"+
    "\1\u013d\43\2\46\0\2\2\4\0\24\2\1\u013e\27\2"+
    "\46\0\2\2\4\0\7\2\1\u0138\44\2\46\0\2\2"+
    "\4\0\44\2\1\u013f\7\2\46\0\2\2\4\0\10\2"+
    "\1\u0140\43\2\46\0\2\2\4\0\23\2\1\u0141\30\2"+
    "\46\0\2\2\4\0\21\2\1\u013c\32\2\46\0\2\2"+
    "\4\0\13\2\1\u0142\40\2\46\0\2\2\4\0\21\2"+
    "\1\u0142\32\2\46\0\2\2\4\0\3\2\1\u0143\50\2"+
    "\46\0\2\2\4\0\3\2\1\u0144\50\2\46\0\2\2"+
    "\4\0\10\2\1\u0145\43\2\46\0\2\2\4\0\10\2"+
    "\1\u0146\43\2\46\0\2\2\4\0\1\u0147\53\2\46\0"+
    "\2\2\4\0\42\2\1\u0148\11\2\46\0\2\2\4\0"+
    "\30\2\1\u0149\23\2\46\0\2\2\4\0\4\2\1\u014a"+
    "\47\2\46\0\2\2\4\0\5\2\1\u014b\46\2\46\0"+
    "\2\2\4\0\44\2\1\u014c\7\2\46\0\2\2\4\0"+
    "\33\2\1\u0149\20\2\46\0\2\2\4\0\11\2\1\u014a"+
    "\42\2\46\0\2\2\4\0\16\2\1\u014d\35\2\46\0"+
    "\2\2\4\0\42\2\1\u014e\11\2\46\0\2\2\4\0"+
    "\24\2\1\u014f\27\2\46\0\2\2\4\0\44\2\1\u0150"+
    "\7\2\46\0\2\2\4\0\35\2\1\u0151\16\2\46\0"+
    "\2\2\4\0\30\2\1\u0152\23\2\46\0\2\2\4\0"+
    "\4\2\1\u0153\47\2\46\0\2\2\4\0\4\2\1\u0154"+
    "\47\2\46\0\2\2\4\0\42\2\1\u0155\11\2\46\0"+
    "\2\2\4\0\37\2\1\u0151\14\2\46\0\2\2\4\0"+
    "\33\2\1\u0152\20\2\46\0\2\2\4\0\11\2\1\u0153"+
    "\42\2\46\0\2\2\4\0\11\2\1\u0156\42\2\46\0"+
    "\2\2\4\0\44\2\1\u0157\7\2\46\0\2\2\4\0"+
    "\34\2\1\u0158\17\2\46\0\2\2\4\0\4\2\1\u0159"+
    "\47\2\46\0\2\2\4\0\36\2\1\u0158\15\2\46\0"+
    "\2\2\4\0\11\2\1\u015a\42\2\46\0\2\2\4\0"+
    "\2\2\1\u015b\51\2\46\0\2\2\4\0\1\u015c\53\2"+
    "\46\0\2\2\4\0\7\2\1\u015b\44\2\46\0\2\2"+
    "\4\0\5\2\1\u015d\46\2\46\0\2\2\4\0\17\2"+
    "\1\u015e\34\2\46\0\2\2\4\0\43\2\1\u015f\10\2"+
    "\46\0\2\2\4\0\25\2\1\u0160\26\2\46\0\2\2"+
    "\4\0\45\2\1\u015f\6\2\46\0\2\2\4\0\15\2"+
    "\1\u0161\36\2\46\0\2\2\4\0\4\2\1\u0162\47\2"+
    "\46\0\2\2\4\0\23\2\1\u0163\30\2\46\0\2\2"+
    "\4\0\11\2\1\u0162\42\2\46\0\2\2\4\0\15\2"+
    "\1\u0164\36\2\46\0\2\2\4\0\23\2\1\u0165\30\2"+
    "\46\0\2\2\4\0\2\2\1\u0166\51\2\46\0\2\2"+
    "\4\0\7\2\1\u0166\44\2\46\0\2\2\4\0\1\2"+
    "\1\u0167\52\2\46\0\2\2\4\0\6\2\1\u0167\45\2"+
    "\46\0\2\2\4\0\16\2\1\u0168\35\2\46\0\2\2"+
    "\4\0\24\2\1\u0169\27\2\46\0\2\2\4\0\16\2"+
    "\1\u016a\35\2\46\0\2\2\4\0\24\2\1\u016b\27\2"+
    "\46\0\2\2\4\0\42\2\1\u016c\11\2\46\0\2\2"+
    "\4\0\44\2\1\u016c\7\2\46\0\2\2\4\0\42\2"+
    "\1\u016d\11\2\46\0\2\2\4\0\44\2\1\u016d\7\2"+
    "\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[25520];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\1\1\11\34\1\2\11\2\1\1\11\2\1"+
    "\31\11\1\0\67\1\10\11\1\0\2\11\101\1\1\11"+
    "\247\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[365];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	
    private int contador;
    private ArrayList<Yytoken> tokens;
    private ArrayList<ErroresC> errores;

	private void writeOutputFile() throws IOException{
			String filename = "file.out";
			BufferedWriter out = new BufferedWriter(
				new FileWriter(filename));
            System.out.println("\n*** Tokens guardados en archivo ***\n");
			for(Yytoken t: this.tokens){
				System.out.println(t);
				out.write(t + "\n");
			}
			out.close();

        //-----------------------------------------------------------------------
            String filenameE = "errores.txt";
			BufferedWriter error = new BufferedWriter(
				new FileWriter(filenameE));
            System.out.println("\n*** Tokens guardados en archivo ***\n");
			for(ErroresC t: this.errores){
				System.out.println(t);
				error.write(t + "\n");
			}
			error.close();

	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
      contador = 0;
	tokens = new ArrayList<Yytoken>();
        errores = new ArrayList<ErroresC>();
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	try{
		this.writeOutputFile();
        //System.exit(0);
	}catch(IOException ioe){
		ioe.printStackTrace();
	}

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"id",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 88: break;
        case 2: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"num",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 89: break;
        case 3: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"gato",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 90: break;
        case 4: 
          { //ignorar
          }
        case 91: break;
        case 5: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"asignacion",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 92: break;
        case 6: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"suma",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 93: break;
        case 7: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"resta",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 94: break;
        case 8: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"multiplicacion",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 95: break;
        case 9: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"division",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 96: break;
        case 10: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"and",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 97: break;
        case 11: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"or",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 98: break;
        case 12: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"not",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 99: break;
        case 13: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"parentesis_apertura",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 100: break;
        case 14: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"parentesis_cierre",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 101: break;
        case 15: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Mayor_que",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 102: break;
        case 16: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Menor_que",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 103: break;
        case 17: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"terminador_sentencia",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 104: break;
        case 18: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"separador",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 105: break;
        case 19: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"puntos_de_rutina",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 106: break;
        case 20: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"comillas",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 107: break;
        case 21: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"llave_apertura",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 108: break;
        case 22: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"llave_cierre",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 109: break;
        case 23: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"corchete_apertura",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 110: break;
        case 24: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"corchete_cierre",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 111: break;
        case 25: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"signo_pesos",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"signo_pesos",yyline);
    errores.add(e);
    return t;
          }
        case 112: break;
        case 26: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"punto",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"punto",yyline);
    errores.add(e);
    return t;
          }
        case 113: break;
        case 27: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"guion_bajo",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"guion_bajo",yyline);
    errores.add(e);
    return t;
          }
        case 114: break;
        case 28: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Porciento",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Porciento",yyline);
    errores.add(e);
    return t;
          }
        case 115: break;
        case 29: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Apertura_interrogacion",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Apertura_interrogacion",yyline);
    errores.add(e);
    return t;
          }
        case 116: break;
        case 30: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Cierre_interrogacion",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Cierre_interrogacion",yyline);
    errores.add(e);
    return t;
          }
        case 117: break;
        case 31: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Apostrofe",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Apostrofe",yyline);
    errores.add(e);
    return t;
          }
        case 118: break;
        case 32: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Acento circunflejo",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Acento circunflejo",yyline);
    errores.add(e);
    return t;
          }
        case 119: break;
        case 33: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Arroba",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Arroba",yyline);
    errores.add(e);
    return t;
          }
        case 120: break;
        case 34: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Acento grave",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Acento grave",yyline);
    errores.add(e);
    return t;
          }
        case 121: break;
        case 35: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Virgulilla",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"Virgulilla",yyline);
    errores.add(e);
    return t;
          }
        case 122: break;
        case 36: 
          { contador++;
     Yytoken t = new Yytoken(contador,yytext(),"diagonal_inversa",yyline,yycolumn);
     tokens.add(t);
     ErroresC e = new ErroresC(yytext(),"diagonal_inversa",yyline);
     errores.add(e);
     return t;
          }
        case 123: break;
        case 37: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"apertura_exclamacion",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"apertura_exclamacion",yyline);
     errores.add(e);
    return t;
          }
        case 124: break;
        case 38: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"dieresis",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"dieresis",yyline);
    errores.add(e);
    return t;
          }
        case 125: break;
        case 39: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"signo_negacion",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"signo_negacion",yyline);
    errores.add(e);
    return t;
          }
        case 126: break;
        case 40: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"signo_grado",yyline,yycolumn);
    tokens.add(t);
    ErroresC e = new ErroresC(yytext(),"signo_grado",yyline);
    errores.add(e);
    return t;
          }
        case 127: break;
        case 41: 
          { contador++;
     Yytoken t = new Yytoken(contador,yytext(),"acento_agudo",yyline,yycolumn);
     tokens.add(t);
     ErroresC e = new ErroresC(yytext(),"acento_agudo",yyline);
     errores.add(e);
     return t;
          }
        case 128: break;
        case 42: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"IF",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 129: break;
        case 43: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"igual que",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 130: break;
        case 44: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Suma_sobre_asignación_previa",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 131: break;
        case 45: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"incremento",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 132: break;
        case 46: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Resta_sobre_asignacion_previa",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 133: break;
        case 47: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"decremento",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 134: break;
        case 48: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Multiplicacion_sobre_asignacion_previa",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 135: break;
        case 49: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Division_sobre_asignacion_previa",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 136: break;
        case 50: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"distinto",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 137: break;
        case 51: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Mayor_igual_que",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 138: break;
        case 52: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"Menor_igual_que",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 139: break;
        case 53: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"RET",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 140: break;
        case 54: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"END",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 141: break;
        case 55: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SET",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 142: break;
        case 56: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"xor",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 143: break;
        case 57: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"CASE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 144: break;
        case 58: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"CALL",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 145: break;
        case 59: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"ELSE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 146: break;
        case 60: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"EXIT",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 147: break;
        case 61: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"TEXT",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 148: break;
        case 62: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"TIME",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 149: break;
        case 63: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"INIT",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 150: break;
        case 64: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"CICLE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 151: break;
        case 65: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"ROUTE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 152: break;
        case 66: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"TABLE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 153: break;
        case 67: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"VIRUS",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 154: break;
        case 68: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"START",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 155: break;
        case 69: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SLEEP",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 156: break;
        case 70: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"CREATE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 157: break;
        case 71: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"BIGINT",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 158: break;
        case 72: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"DEFINE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 159: break;
        case 73: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SWITCH",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 160: break;
        case 74: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"GROWTH",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 161: break;
        case 75: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"ECONOMY",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 162: break;
        case 76: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"TINYINT",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 163: break;
        case 77: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"DECIMAL",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 164: break;
        case 78: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"DESTROY",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 165: break;
        case 79: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SEGMENT",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 166: break;
        case 80: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"PROGRAM",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 167: break;
        case 81: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"RESOURCE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 168: break;
        case 82: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"BUILDING",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 169: break;
        case 83: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SMALLINT",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 170: break;
        case 84: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"REFERENCE",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 171: break;
        case 85: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"BEHAVIOUR",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 172: break;
        case 86: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SIMULATION",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 173: break;
        case 87: 
          { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"POPULATION",yyline,yycolumn);
    tokens.add(t);
    return t;
          }
        case 174: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
